waiting to receive
sending "hi"
sending "asd"
sending "asdf"
sending "as"
sending "fd"
sending "asdf"
sending "asdf"
sending "asfd"
sending "as"
sending "fsa"
sending "df"
sending "asdf"
sending "asdf"
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "client.py", line 63, in rec
    data, server = sock.recvfrom(4096)
timeout: timed out

sending "asdf"
sending "as"
sending "dfa"
sending "d"
sending "a"
sending "a"
sending "asdf"
sending "a"
sending "sdfa"
sending "sdf"
sending "asdfqw"
sending "eq"
sending "we"
sending "qwe"
sending "qwe"
sending "qwe"
sending "qwe"
sending "q"
sending "weq"
sending "we"
sending "qwe"
sending "qw"
sending "eq"
sending "we"
sending "qwe"
sending "q"
sending "weq"
sending "we"
sending "qe"
sending "q"
sending "eq"
sending "eq"
sending "we"
sending "qe"
sending "q"
sending "eq"
sending "eq"
sending "eq"
sending "e"
sending "q"
sending "a"
sending "sd"
sending "ad"
sending "q"
sending "we"
sending "wx"
sending "g'dr"
sending "thd"
sending "fhd"
sending "fh"
sending "rt"
sending "sfxaf"
Traceback (most recent call last):
  File "client.py", line 100, in <module>
    send(ih,sock)
  File "client.py", line 73, in send
    ipt = cht.getIpt()
  File "client.py", line 20, in getIpt
    return self.screen.getstr(0,0,curses.COLS)
KeyboardInterrupt
